services:
  rasa-pinger:
    image: khalosa/rasa-aarch64:3.5.2
    networks: ["rasa-project2"]
    ports:
      - "5005:5005"
    volumes:
      - "./:/app/"
    command:
      - run
      - -vv
      - --enable-api
      - --cors
      - "*"
  action-service-pinger:
    image: pinger_requirements:latest
    networks: ["rasa-project2"]
    ports:
      - "5055:5055"
    volumes:
      - "./actions:/app/actions"
networks: { rasa-project2: {} }
